export const DOCS_CATEGORY_GROUP = {
  Layout: 'Layout',
  Navigation: 'Navigation',
  Disclosure: 'Disclosure',
  Overlays: 'Overlays',
  Forms: 'Forms',
  DataDisplay: 'Cards & Highlights',
  MediaGalleries: 'Media & Galleries',
  AnimationMotion: 'Animation & Motion',
  VisualEffects: 'Visual Effects',
  Visual3D: '3D & Visuals',
  Utilities: 'Utilities',
} as const;

export const DOCS_CATEGORY_KEY = {
  'liquid-glass': 'liquid-glass',
  'color-picker': 'color-picker',
  buttons: 'buttons',
  noise: 'noise',
  globe: 'globe',
  footers: 'footers',
  'responsive-header': 'responsive-header',
  'buy-me-coffee': 'buy-me-coffee',
  swapy: 'swapy',
  'drag-items': 'drag-items',
  'image-ripple-effect': 'image-ripple-effect',
  'r3f-blob': 'r3f-blob',
  'mesh-gradients': 'mesh-gradients',
  'blur-vignette': 'blur-vignette',
  'motion-number': 'motion-number',
  'uilayouts-github-button': 'uilayouts-github-button',
  'liquid-gradient': 'liquid-gradient',
  'range-slider': 'range-slider',
  password: 'password',
  'tags-input': 'tags-input',
  'phone-input': 'phone-input',
  'datetime-picker': 'datetime-picker',
  'multi-selector': 'multi-selector',
  'file-upload': 'file-upload',
  'clip-path': 'clip-path',
  'image-masking': 'image-masking',
  'video-masking': 'video-masking',
  'hover-cards': 'hover-cards',
  'product-cards': 'product-cards',
  'gradient-border': 'gradient-border',
  'spotlight-cards': 'spotlight-cards',
  'timeline-animation': 'timeline-animation',
  'scroll-animation': 'scroll-animation',
  'scroll-text': 'scroll-text',
  'scroll-text-marquee': 'scroll-text-marquee',
  'randomized-text-effect': 'randomized-text-effect',
  'image-mousetrail': 'image-mousetrail',
  'image-reveal': 'image-reveal',
  'progressive-carousel': 'progressive-carousel',
  blocks: 'blocks',
  'animated-beam': 'animated-beam',
  dialog: 'dialog',
  'media-modal': 'media-modal',
  'linear-modal': 'linear-modal',
  'gallery-modal': 'gallery-modal',
  'responsive-modal': 'responsive-modal',
  'directional-drawer': 'directional-drawer',
  'motion-drawer': 'motion-drawer',
  'right-motion-drawer': 'right-motion-drawer',
  'horizontal-scroll': 'horizontal-scroll',
  'stacking-card': 'stacking-card',
  'smooth-scroll': 'smooth-scroll',
  'sticky-scroll': 'sticky-scroll',
  tabs: 'tabs',
  'image-tabs': 'image-tabs',
  'magnified-doc': 'magnified-doc',
  sparkles: 'sparkles',
  'sparkles-title': 'sparkles-title',
  carousel: 'carousel',
  'framer-carousel': 'framer-carousel',
  accordion: 'accordion',
  faqs: 'faqs',
  'image-accordions': 'image-accordions',
  grid: 'grid',
  'masonary-grid': 'masonary-grid',
  marquee: 'marquee',
  'infinity-brand': 'infinity-brand',
} as const;

export type DocsCategoryKey = (typeof DOCS_CATEGORY_KEY)[keyof typeof DOCS_CATEGORY_KEY];

export type DocsCategoryGroup = (typeof DOCS_CATEGORY_GROUP)[keyof typeof DOCS_CATEGORY_GROUP];

export interface DocsNavigationCategory {
  href: string;
  name: string;
  key: DocsCategoryKey
  group: DocsCategoryGroup;
  tags: string[];
  new?: boolean;
  updated?: boolean;
}


export const DocsNavigationCategories: DocsNavigationCategory[] = [
  {
    href: '/components/liquid-glass',
    name: 'Liquid-Glass',
    key: DOCS_CATEGORY_KEY['liquid-glass'],
    group: DOCS_CATEGORY_GROUP.VisualEffects,
    new: true,
    tags: [
      'Liquid-Glass',
      'liquid glass',
      'liquid glass component',
      'liquid glass card',
      'liquid glass weather',
      'liquid glass weather component',
      'liquid glass notification',
      'liquid glass notification component',
      'liquid glass mobile icons',
      'liquid glass mobile icons component',
      'liquid glass sidebar menu',
      'liquid glass sidebar menu component',
    ],
  },
  {
    href: '/components/swapy',
    name: 'Swapy Drag',
    key: DOCS_CATEGORY_KEY['swapy'],
    group: DOCS_CATEGORY_GROUP.AnimationMotion,
    new: true,
    updated: false,
    tags: [
      'Swapy drag',
      'swapy draggable',
      'swapy items',
      'swapy sortable',
      'swapy list',
    ],
  },
  {
    href: '/components/dialog',
    name: 'Dialog',
    key: DOCS_CATEGORY_KEY['dialog'],
    group: DOCS_CATEGORY_GROUP.Overlays,
    tags: ['dialog', 'popup', 'modal', 'UI-component'],
  },
  {
    href: '/components/color-picker',
    name: 'Color Picker',
    key: DOCS_CATEGORY_KEY['color-picker'],
    group: DOCS_CATEGORY_GROUP.Forms,
    tags: [],
  },
  {
    href: '/components/buttons',
    name: 'Buttons',
    key: DOCS_CATEGORY_KEY['buttons'],
    group: DOCS_CATEGORY_GROUP.Forms,
    tags: [],
    updated: false,
  },
  {
    href: '/components/noise',
    name: 'Noise',
    key: DOCS_CATEGORY_KEY['noise'],
    group: DOCS_CATEGORY_GROUP.VisualEffects,
    new: false,
    tags: ['noise', 'effect', 'visual', 'distortion', 'shader'],
  },
  {
    href: '/components/globe',
    name: 'Globe',
    key: DOCS_CATEGORY_KEY['globe'],
    group: DOCS_CATEGORY_GROUP.Visual3D,
    tags: ['threejs', '3d globe', 'r3f globe', 'cobe', 'code globe example'],
  },
  {
    href: '/components/footers',
    name: 'Footers',
    key: DOCS_CATEGORY_KEY['footers'],
    group: DOCS_CATEGORY_GROUP.Layout,
    tags: [
      'footer',
      'animation',
      'logo',
      'branding',
      'animated',
      'hover',
      'interactive',
    ],
  },

  {
    href: '/components/buy-me-coffee',
    name: 'Buy Me A Coffee',
    key: DOCS_CATEGORY_KEY['buy-me-coffee'],
    group: DOCS_CATEGORY_GROUP.DataDisplay,
    tags: [
      'Sponser',
      'Buy me a coffee',
      'co-fi',
      'Buy-me-a-coffee',
      'supports',
    ],
  },

  {
    href: '/components/drag-items',
    name: 'Drag Items',
    key: DOCS_CATEGORY_KEY['drag-items'],
    updated: false,
    group: DOCS_CATEGORY_GROUP.AnimationMotion,

    tags: ['drag', 'draggable', 'items', 'sortable', 'list'],
  },
  {
    href: '/components/image-ripple-effect',
    name: 'Img Ripple Effect',
    key: DOCS_CATEGORY_KEY['image-ripple-effect'],
    group: DOCS_CATEGORY_GROUP.Visual3D,
    tags: [
      'img-ripple-effect',
      'image ripple effect',
      'images-ripple-effect',
      'threejs ripple effect',
      'React three Fiber Ripple Effect',
    ],
  },
  {
    href: '/components/r3f-blob',
    name: 'R3F Blob',
    key: DOCS_CATEGORY_KEY['r3f-blob'],
    group: DOCS_CATEGORY_GROUP.Visual3D,
    new: true,
    tags: ['r3f-blob', 'threejs blob', 'animated blob', 'blob'],
  },
  {
    href: '/components/mesh-gradients',
    name: 'Mesh Gradients',
    key: DOCS_CATEGORY_KEY['mesh-gradients'],
    group: DOCS_CATEGORY_GROUP.Visual3D,
    new: true,
    tags: [
      'mesh-gradient',
      'Mesh Gradients',
      'Gradients',
      'r3f gradients',
      'threejs gradients',
    ],
  },
  {
    href: '/components/blur-vignette',
    name: 'Blur Vignette',
    key: DOCS_CATEGORY_KEY['blur-vignette'],
    group: DOCS_CATEGORY_GROUP.VisualEffects,
    tags: [
      'blur-sm',
      'vignette',
      'video',
      'blur-vignette',
      'background',
      'overlay',
      'effect',
      'media',
      'visual-effect',
      'image',
      'blur-effect',
      'vignette-img',
      'fade',
      'card',
      'blur-card',
      'background-effect',
      'shadow-sm',
      'card-design',
    ],
  },
  {
    href: '/components/motion-number',
    name: 'Motion Number',
    key: DOCS_CATEGORY_KEY['motion-number'],
    group: DOCS_CATEGORY_GROUP.Forms,
    tags: [
      'animation',
      'number-animation',
      'input',
      'input animation',
      'motion number input',
      'number-flow',
      'number flow',
      'number-increment',
      'counter',
      'trading',
      'motion number trading',
      'post-effect',
      'shadcn slider',
      'animated slider tag',
      'motion number slider',
      'number-sequence',
      'upvotes',
      'motion number',
      'motion-number',
      'like dislikes',
      'like-dislikes',
      'downvotes',
    ],
  },
  {
    href: '/components/liquid-gradient',
    name: 'liquid-gradient',
    key: DOCS_CATEGORY_KEY['liquid-gradient'],
    group: DOCS_CATEGORY_GROUP.VisualEffects,
    tags: [
      'uilayouts',
      'github',
      'button',
      'liquid-gradient',
      'Liquid Gradient',
      'github-button',
      'uilayouts github button',
      'repository',
      'link',
      'cta',
      'stars',
      'fork',
      'open-source',
      'profile',
    ],
  },
  {
    href: '/components/range-slider',
    name: 'Range Slider',
    key: DOCS_CATEGORY_KEY['range-slider'],
    group: DOCS_CATEGORY_GROUP.Forms,
    tags: [
      'input slider',
      'Default range slider',
      'default-Range-Slider',
      'animated motion number slider',
      'motion input slider',
      'dual range slider',
      'Dual-Range-Slider',
      'static range slider',
      'Static-Range-Slider',
      'Basic Range-Slider',
      'Default Range-Slider',
      'position range slider',
      'Position-Range-Slider',
      'Position Range-Slider',
      'form component',
      'input',
      'user interface',
    ],
  },
  {
    href: '/components/password',
    name: 'Password',
    key: DOCS_CATEGORY_KEY['password'],
    group: DOCS_CATEGORY_GROUP.Forms,
    tags: [
      'password',
      'pass',
      'password hide show icon',
      'showhide pass',
      'show/hide pass',
      'Show/Hide Pass',
      'Pass Show/Hide ',
      'Pass Strength Indicator',
      'pass-strength-indicator',
      'Progress Password Input',
      'ProgressPasswordInput',
      'Pass Strength Indicator2',
      'pass-strength-indicator2',
      'Progress Password2',
      'ProgressPasswordInput2',
      'Strong Pass Hover Indicator',
      'Hover Indicator',
      'Divide Progress Password ',
      'Progress Divide Password2 ',
      'DivideProgressPasswordInput2',
      'Inline Pass Indicator',
      'Password Status Indicator',
      'Pass Status Indicator',
      'Status Password ',
      'StatusPasswordInput',
      'Confirm pass',
      'Confirm Pass With Indicator',
      'Confirm Password Check',
      'Confirm Password',
      'form component',
      'input',
      'user interface',
    ],
  },
  {
    href: '/components/tags-input',
    name: 'UTube Tags',
    key: DOCS_CATEGORY_KEY['tags-input'],
    group: DOCS_CATEGORY_GROUP.Forms,
    tags: [
      'Tags Input',
      'Tags Edit False',
      'Youtube Tags',
      'Github Like Tags',
      'github tags',
      'input tags',
      'form component',
      'input',
      'user interface',
    ],
  },
  {
    href: '/components/phone-input',
    name: 'Phone Input',
    key: DOCS_CATEGORY_KEY['phone-input'],
    group: DOCS_CATEGORY_GROUP.Forms,
    tags: [
      'phone-input',
      'Phone Input',
      'Input',
      'form component',
      'input',
      'user interface',
    ],
  },
  {
    href: '/components/datetime-picker',
    name: 'Datetime Picker',
    key: DOCS_CATEGORY_KEY['datetime-picker'],
    group: DOCS_CATEGORY_GROUP.Forms,
    tags: [
      'time picker',
      'time-picker',
      'Time Picker',
      'date picker',
      'date-picker',
      'Date Picker',
      'date time picker',
      'date-time picker',
      'DateTime Picker',
      'form component',
      'input',
      'user interface',
    ],
  },
  {
    href: '/components/multi-selector',
    name: 'Multi Selector',
    key: DOCS_CATEGORY_KEY['multi-selector'],
    group: DOCS_CATEGORY_GROUP.Forms,
    tags: [
      'Multi Selector Input',
      'Selector Input Tag',
      'Multiple Selector Input',
      'form component',
      'input',
      'user interface',
    ],
  },
  {
    href: '/components/file-upload',
    name: 'File Upload',
    key: DOCS_CATEGORY_KEY['file-upload'],
    new: false,
    group: DOCS_CATEGORY_GROUP.Forms,
    tags: [
      'DropZone input',
      'File Upload Input ',
      'file-upload',
      'file upload preview',
      'chat box upload file',
      'Chat Box',
      'Chat-Box',
      'Img preview',
      'form component',
      'input',
      'user interface',
    ],
  },
  {
    href: '/components/clip-path',
    name: 'Clip-Path ',
    key: DOCS_CATEGORY_KEY['clip-path'],
    new: false,
    group: DOCS_CATEGORY_GROUP.MediaGalleries,
    tags: ['clip-path', 'creative', 'masking', 'corporate', 'symbolic', 'mask'],
  },
  {
    href: '/components/image-masking',
    name: 'Image Masking',
    key: DOCS_CATEGORY_KEY['image-masking'],
    new: false,
    group: DOCS_CATEGORY_GROUP.MediaGalleries,
    tags: [
      'image-masking',
      'creative',
      'masking',
      'animal-image-masking',
      'Animal Image Masking ',
      'center-image-masking',
      'background Image Masking ',
      'fixedbg-image-masking',
      'Fixed BG Image Masking ',
      'Watersplash-image-masking',
      'Water Splash Image Masking ',
      'BG Image Masking ',
    ],
  },
  {
    href: '/components/video-masking',
    name: 'Video Masking',
    key: DOCS_CATEGORY_KEY['video-masking'],
    new: false,
    group: DOCS_CATEGORY_GROUP.MediaGalleries,
    tags: [
      'video',
      'masking',
      'creative',
      'splash',
      'hexagon video masking',
      ' hexagon masking',
      'hexagon video masking2',
      ' hexagon masking2',
      'text overlay video',
      'text-overlay video masking',
    ],
  },
  {
    href: '/components/hover-cards',
    name: 'Hover cards',
    key: DOCS_CATEGORY_KEY['hover-cards'],
    group: DOCS_CATEGORY_GROUP.DataDisplay,
    tags: [
      'hover',
      'stripe',
      'card',
      'animation',
      'interaction',
      'design',
      'ui',
      'style',
      'ui card',
      'component',
    ],
  },
  {
    href: '/components/product-cards',
    name: 'Product-Cards',
    key: DOCS_CATEGORY_KEY['product-cards'],
    group: DOCS_CATEGORY_GROUP.DataDisplay,
    tags: [
      'product',
      'card',
      'ui',
      'design',
      'ecommerce',
      'style',
      'ui card',
      'component',
    ],
  },
  {
    href: '/components/gradient-border',
    name: 'gradient-border',
    key: DOCS_CATEGORY_KEY['gradient-border'],
    group: DOCS_CATEGORY_GROUP.DataDisplay,
    tags: [
      'gradient',
      'border',
      'card',
      'background',
      'style',
      'design',
      'ui',
      'effect',
      'ui card',
      'component',
    ],
  },
  {
    href: '/components/spotlight-cards',
    name: 'Spotlight cards',
    key: DOCS_CATEGORY_KEY['spotlight-cards'],
    group: DOCS_CATEGORY_GROUP.VisualEffects,
    tags: [
      'spotlight',
      'card',
      'ui',
      'design',
      'highlight',
      'feature',
      'ui card',
      'component',
    ],
  },
  {
    href: '/components/timeline-animation',
    name: 'Timeline Animation',
    key: DOCS_CATEGORY_KEY['timeline-animation'],
    group: DOCS_CATEGORY_GROUP.AnimationMotion,
    new: false,
    updated: true,
    tags: [
      'timeline-animation',
      'timeline animation',
      'animation',
      'scroll',
      'motion',
      'interactive',
    ],
  },
  {
    href: '/components/scroll-animation',
    name: 'Scroll Animation',
    key: DOCS_CATEGORY_KEY['scroll-animation'],
    new: false,
    updated: true,
    group: DOCS_CATEGORY_GROUP.AnimationMotion,
    tags: [
      'scroll',
      'animation',
      'element',
      'repeat',
      'text',
      'motion',
      'interactive',
    ],
  },
  {
    href: '/components/scroll-text',
    name: 'Scroll Text',
    key: DOCS_CATEGORY_KEY['scroll-text'],
    new: false,
    updated: true,
    group: DOCS_CATEGORY_GROUP.AnimationMotion,
    tags: ['scroll', 'text', 'animation'],
  },
  {
    href: '/components/scroll-text-marquee',
    name: 'Text Maruqee',
    key: DOCS_CATEGORY_KEY['scroll-text-marquee'],
    group: DOCS_CATEGORY_GROUP.AnimationMotion,
    tags: ['marquee', 'text', 'animation'],
  },
  {
    href: '/components/randomized-text-effect',
    name: 'Randomized Text',
    key: DOCS_CATEGORY_KEY['randomized-text-effect'],
    group: DOCS_CATEGORY_GROUP.AnimationMotion,
    new: false,
    tags: ['random', 'text', 'effect'],
  },
  {
    href: '/components/image-mousetrail',
    name: 'Image Mousetrail',
    key: DOCS_CATEGORY_KEY['image-mousetrail'],
    group: DOCS_CATEGORY_GROUP.AnimationMotion,
    new: false,
    tags: [
      'mouse-trail',
      'animation',
      'image-effect',
      'motion-trail',
      'small-images',
      'interactive',
      'disappearing-effect',
      'interactive-animation',
      'mouse-motion',
      'Without Component Mousetrail',
      'Image Mouse Trail Without Components',
    ],
  },
  {
    href: '/components/image-reveal',
    name: 'Image Reveal',
    key: DOCS_CATEGORY_KEY['image-reveal'],
    group: DOCS_CATEGORY_GROUP.VisualEffects,
    tags: [
      'image',
      'reveal',
      'image-reveal',
      'transition',
      'animation',
      'hover-effect',
      'scroll-reveal',
      'gallery',
      'fade-in',
      'image-reveal2',
      'scroll',
      'parallax',
      'fade',
    ],
  },
  {
    href: '/components/progressive-carousel',
    name: 'Progressive Carousel',
    key: DOCS_CATEGORY_KEY['progressive-carousel'],
    new: false,
    group: DOCS_CATEGORY_GROUP.MediaGalleries,
    tags: [
      'carousel',
      'horizontal',
      'progressive-carousel',
      'scroll-carousel',
      'vertical',
      'vertical-scroll',
    ],
  },
  {
    href: '/components/blocks',
    name: 'Blocks',
    key: DOCS_CATEGORY_KEY['blocks'],
    group: DOCS_CATEGORY_GROUP.VisualEffects,
    tags: [
      'blocks',
      'background',
      'bg-blocks',
      'layout',
      'design',
      'grid',
      'tiles',
      'bg-effect',
    ],
  },
  {
    href: '/components/animated-beam',
    name: 'Animated Beam',
    key: DOCS_CATEGORY_KEY['animated-beam'],
    group: DOCS_CATEGORY_GROUP.VisualEffects,
    tags: [
      'animated',
      'beam',
      'default',
      'animation',
      'effect',
      'motion',
      'visual',
      'light-beam',
      'bidirectional',
      'light',
      'visual-motion',
      'unidirectional',
      'multiple-input',
      'data-input',
      'multiple-output',
      'visual-output',
    ],
  },

  {
    href: '/components/media-modal',
    name: 'Media Modal',
    key: DOCS_CATEGORY_KEY['media-modal'],
    group: DOCS_CATEGORY_GROUP.Overlays,
    tags: ['media', 'modal', 'popup', 'UI', 'image modal'],
  },
  {
    href: '/components/linear-modal',
    name: 'Linear Modal',
    key: DOCS_CATEGORY_KEY['linear-modal'],
    group: DOCS_CATEGORY_GROUP.Overlays,
    updated: true,
    tags: [
      'card',
      'linear-layout',
      'linear-modal',
      'linear-card',
      'UI-component',
      'modal-card',
    ],
  },
  {
    href: '/components/gallery-modal',
    name: 'Gallery Modal',
    key: DOCS_CATEGORY_KEY['gallery-modal'],
    group: DOCS_CATEGORY_GROUP.Overlays,
    tags: [
      'gallery',
      'accordion',
      'modal',
      'media',
      'slider',
      'media-modal',
      'interactive',
      'unsplash',
      'image-gallery',
    ],
  },
  {
    href: '/components/responsive-modal',
    name: 'Responsive Modal',
    key: DOCS_CATEGORY_KEY['responsive-modal'],
    group: DOCS_CATEGORY_GROUP.Overlays,
    updated: true,
    tags: ['drawer', 'responsive drawer', 'navigation', 'responsive', 'menu'],
  },

  {
    href: '/components/directional-drawer',
    name: 'Directional Drawer',
    key: DOCS_CATEGORY_KEY['directional-drawer'],
    new: true,
    group: DOCS_CATEGORY_GROUP.Overlays,
    tags: [
      'sidebar',
      'vaul',
      'navigation',
      'drawer',
      'responsive',
      'Left Sidebar',
      'right drawer',
      'top drawer',
      'bottom drawer',
      'Left Drawer',
      'directional drawer',
      'Responsive Drawer',
    ],
  },
  {
    href: '/components/motion-drawer',
    name: 'Motion Drawer',
    key: DOCS_CATEGORY_KEY['motion-drawer'],
    group: DOCS_CATEGORY_GROUP.Overlays,
    new: true,
    tags: [
      'sidebar',
      'navigation',
      'drawer',
      'responsive',
      'Left Sidebar',
      'right drawer',
      'framer-motion drawer',
      'motion drawer',
    ],
  },
  {
    href: '/components/responsive-header',
    name: 'Responsive-Header',
    key: DOCS_CATEGORY_KEY['responsive-header'],
    group: DOCS_CATEGORY_GROUP.Layout,
    updated: true,
    tags: ['header', 'responsive', 'navigation-bar', 'menu'],
  },
  {
    href: '/components/horizontal-scroll',
    name: 'Horizontal Scroll',
    key: DOCS_CATEGORY_KEY['horizontal-scroll'],
    group: DOCS_CATEGORY_GROUP.AnimationMotion,
    tags: [
      'White 3D Globe',
      'White 3D Globe Card',
      'horizontal',
      'scroll',
      'framer',
    ],
  },
  {
    href: '/components/stacking-card',
    name: 'Stacking Card',
    key: DOCS_CATEGORY_KEY['stacking-card'],
    group: DOCS_CATEGORY_GROUP.AnimationMotion,
    tags: [
      'Card Stack',
      'Interactive Cards',
      'CSS Stacking',
      'Details Card',
      'CSS Image Stack',
      'Stacking Card',
    ],
  },
  {
    href: '/components/smooth-scroll',
    name: 'Smooth-Scroll',
    key: DOCS_CATEGORY_KEY['smooth-scroll'],
    group: DOCS_CATEGORY_GROUP.AnimationMotion,
    tags: ['Smooth Scrolling', 'Lenis Smooth Scroll', 'Scroll Animation'],
  },
  {
    href: '/components/sticky-scroll',
    name: 'Sticky Scroll',
    key: DOCS_CATEGORY_KEY['sticky-scroll'],
    group: DOCS_CATEGORY_GROUP.AnimationMotion,
    new: false,
    tags: [
      'Sticky Scroll',
      'Section',
      'Sticky Gallery',
      'Gallery Scroll',
      'Sticky Hero',
      'Hero Section',
    ],
  },
  {
    href: '/components/tabs',
    name: 'Tabs',
    key: DOCS_CATEGORY_KEY['tabs'],
    group: DOCS_CATEGORY_GROUP.Navigation,
    tags: [
      'tabs',
      'ui',
      'navigation',
      'component',
      'design',
      'creative',
      'form',
      'registration',
    ],
  },
  {
    href: '/components/image-tabs',
    name: 'Image Tabs',
    key: DOCS_CATEGORY_KEY['image-tabs'],
    group: DOCS_CATEGORY_GROUP.Navigation,
    tags: ['tabs', 'image', 'ui', 'gallery', 'design'],
  },
  {
    href: '/components/magnified-doc',
    name: 'Magnified-Doc',
    key: DOCS_CATEGORY_KEY['magnified-doc'],
    group: DOCS_CATEGORY_GROUP.Navigation,
    tags: ['tabs', 'ui', 'magnified', 'document', 'design'],
  },
  {
    href: '/components/sparkles',
    name: 'Sparkles',
    key: DOCS_CATEGORY_KEY['sparkles'],
    group: DOCS_CATEGORY_GROUP.AnimationMotion,
    tags: [
      'sparkles',
      '3d globe sparkles',
      'animation sparkles',
      'sparkles particle',
    ],
  },
  {
    href: '/components/sparkles-title',
    name: 'Sparkles Title',
    key: DOCS_CATEGORY_KEY['sparkles-title'],
    group: DOCS_CATEGORY_GROUP.AnimationMotion,
    tags: ['sparkles title', 'mousemove sparkles'],
  },
  {
    href: '/components/carousel',
    name: 'Carousel',
    key: DOCS_CATEGORY_KEY['carousel'],
    updated: true,
    group: DOCS_CATEGORY_GROUP.MediaGalleries,
    tags: [
      'carousel',
      'default',
      'slider',
      'basic-slider',
      'embla-carousel',
      'align',
      'centered',
      'alignment-slider',
      'classname',
      'custom-slider',
      'themed-slider',
      'number',
      'numeric-slider',
      'counter-slider',
      'scale',
      'zoom-slider',
      'scalable-carousel',
      'thumbnail',
      'preview-slider',
      'image-carousel',
      'autostart',
      'auto-slider',
      'autoplay-carousel',
    ],
  },
  {
    href: '/components/framer-carousel',
    name: 'Framer Carousel',
    key: DOCS_CATEGORY_KEY['framer-carousel'],
    group: DOCS_CATEGORY_GROUP.MediaGalleries,
    updated: true,
    tags: [
      'carousel',
      'motion/react',
      'animated-carousel',
      'carousel-2',
      'carousel-1',
    ],
  },
  {
    href: '/components/accordion',
    name: 'Accordion',
    key: DOCS_CATEGORY_KEY['accordion'],
    group: DOCS_CATEGORY_GROUP.Disclosure,
    updated: true,
    tags: [
      'accordion',
      'faqs accordion',
      'layout',
      'expandable',
      'collapsible',
      'single',
      'multi',
    ],
  },
  {
    href: '/components/faqs',
    name: 'FAQs',
    key: DOCS_CATEGORY_KEY['faqs'],
    group: DOCS_CATEGORY_GROUP.Disclosure,
    tags: [
      'accordion',
      'faq',
      'questions',
      'answers',
      'expandable',
      'collapsible',
    ],
  },
  {
    href: '/components/image-accordions',
    name: 'Image Accordion',
    key: DOCS_CATEGORY_KEY['image-accordions'],
    group: DOCS_CATEGORY_GROUP.Disclosure,
    tags: [
      'accordion',
      'image',
      'hover',
      'interactive',
      'expandable',
      'tailwind',
      'responsive',
    ],
  },
  {
    href: '/components/grid',
    name: 'Grid',
    key: DOCS_CATEGORY_KEY['grid'],
    group: DOCS_CATEGORY_GROUP.Layout,
    tags: [
      'grid',
      'Normal Grid',
      'normal grid',
      'normalgrid',
      'box grid',
      'Box Grid',
      'condition grid',
      'Contidion Grid',
      'unsplash grid',
      'Unsplash Grid',
    ],
  },
  {
    href: '/components/masonary-grid',
    name: 'Masonary',
    key: DOCS_CATEGORY_KEY['masonary-grid'],
    group: DOCS_CATEGORY_GROUP.Layout,
    tags: ['bento grid', 'grid', 'masonary grid'],
  },
  {
    href: '/components/marquee',
    name: 'Marquee',
    key: DOCS_CATEGORY_KEY['marquee'],
    group: DOCS_CATEGORY_GROUP.AnimationMotion,
    tags: ['default', 'marquee', 'animation', 'vertical', 'logos', '3d'],
  },
  {
    href: '/components/infinity-brand',
    name: 'Infinity Brand',
    key: DOCS_CATEGORY_KEY['infinity-brand'],
    group: DOCS_CATEGORY_GROUP.AnimationMotion,
    tags: ['infinity', 'brand', 'marquee'],
  },
];